"""add languages and language_translations

Revision ID: 2d28cd843cfd
Revises: 8b44d6aef59c
Create Date: 2025-07-16 15:37:00.796248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d28cd843cfd'
down_revision: Union[str, Sequence[str], None] = '8b44d6aef59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('language_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_code', 'locale', name='uq_language_locale')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_translations')
    op.drop_table('languages')
    # ### end Alembic commands ###
