version: "3"

services:
  livekit-server:
    image: livekit/livekit-server
    command: ["--dev", "--bind", "0.0.0.0"]
    ports:
      - "7880:7880" # HTTP API 포트
      - "7881:7881" # WebRTC TCP 포트
      - "7882:7882/udp" # WebRTC UDP 포트
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret
