version: "3"

services:
  livekit-server:
    image: livekit/livekit-server:v1.8.3
    command: ["--dev", "--bind", "0.0.0.0"]  
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=secret

  egress:
    image: livekit/egress:v1.8.3
    restart: unless-stopped
    environment:
      - EGRESS_CONFIG_FILE=/config/config.yaml
    volumes:
      - /dev/null:/config/config.yaml
    depends_on:
      - livekit-server
